// Library entry — programmatic API
export { runInit } from './commands/init'
export { runAdd } from './commands/add'
export { runBuild } from './commands/build'
export { loadConfig, writeConfig } from './utils/config'
export { fetchRegistryItem, resolveRegistryURL } from './utils/registry'
export { resolveItems } from './utils/resolver'
export { transformFile } from './utils/transformer'
export { detectFramework } from './utils/framework'
export { detectPackageManager } from './utils/pm'
export type { ComponentsConfig } from './schemas/config'
export type { RegistryItem, RegistryItemFile, RegistryManifest } from './schemas/registry'
export type { BuildResult } from './commands/build'
export type { ResolvedTree } from './utils/resolver'
